name: Build SafetyCalc EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Build EXE
      run: npx electron-builder --win --portable

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SafetyCalc-EXE
        path: dist/*.exe
